### ISSUE TITLE
Update Pushwoosh for Xamarin

### ISSUE THREAD

**Issue by KevinvdBurg** [Pushwoosh/pushwoosh-xamarin#32] opened 2021-01-05 08:43 UTC
I want to update my app to use the latest standard and drop support for the Android.Support libraries.
The current bindings are 8 months old and do not support AndroidX.

Is it possible to update the bindings and support AndroidX?

Thanks in advance!

**Comment by wfhm** [comment] 2021-01-05 12:01
@KevinvdBurg,

The plugin update is scheduled for January. After migrating to Pushwoosh Android SDK 6.+, it will be compatible with AndroidX out of the box.

**Comment by gerardvanderkruijs** [comment] 2021-01-20 09:16
Hi @wfhm ,
Thanks for the indication of the Pushwoosh Android SDK 6+ release!
Is there any chance you could be a little more specific for the planned release date of this update?
We are currently in the middle of updating multiple apps to AndroidX and it would really help if we know when to expect this update so we can adjust our planning accordingly and also manage the expectations of our clients.

Pushwoosh is the last package in all of our apps that hasn't been updated to support AndroidX, so it would be really great if this update comes as soon as possible.

Thanks in advance!

**Comment by dhiraj-shetty** [comment] 2021-01-22 00:03
Dear Vitaly,

Reference: https://github.com/Pushwoosh/pushwoosh-xamarin/issues/30

There seems to be a lot of demand for migration to AndroidX. Please guide on the expected timelines.

Regards,
Dhiraj.

**Comment by gerardvanderkruijs** [comment] 2021-02-01 08:41
Not to be a annoying impatient developer, but it's February and we haven't heard anything regarding this issue. Could you please give us an update on the Pushwoosh.Xamarin.Droid release?

**Comment by wfhm** [comment] 2021-02-02 12:44
@dhiraj-shetty, @gerardvandercruijs,

Updating Xamarin package is in our current production sprint, so we are already working on it. I will provide a more precise ETA on it shortly.

**Comment by gerardvanderkruijs** [comment] 2021-02-11 12:59
@wfhm 
Come on guys! Again you keep me waiting for 9 days with no answer or update on this issue.
We are paying $3,000 a year for your software, I believe it is only fair we can expect some support and regular SDK updates for this.

**Comment by KevinvdBurg** [comment] 2021-02-11 14:22
I agree with @gerardvanderkruijs,
Regular SDK updates should be in every sprint, not once per year.

**Comment by wfhm** [comment] 2021-02-26 10:58
@KevinvdBurg @gerardvanderkruijs @dhiraj-shetty

The ETA for the 6.0.0 release is mid-March. I will provide a more precise one in a few days.

**Comment by CristianValencia** [comment] 2021-03-12 03:05
Mid March is very close and we do not see any further details on the release. You guys are the only reason why we cannot migrate, and some features are getting delayed and delayed because of this. If Pushwoosh were free I would completely understand all the delays, but big money is put into your service and we expect a minimum of consideration. If we take a look at the time AndroidX appeared into scene, it is really incredibly long period of time. Please take action and give further details.

**Comment by KevinvdBurg** [comment] 2021-03-18 08:59
I just received an e-mail that there is now support for HMS services, but there is no update for the pushwoosh-xamarin package. But it is mid-march, can we expect and update soon?

**Comment by wfhm** [comment] 2021-03-18 14:30
@KevinvdBurg, @CristianValencia,

We had to delay the release in favor of an urgent fix in our native Android SDK (released yesterday). We already started working on updating the plugin once again, but the ETA shifted to April. Please let me explain why it takes us so long - we are moving the Xamarin package from 5.x.x SDK architecture to 6.x.x and also we migrate it to AndroidX, and we have to resolve all the issues for 3 main Pushwoosh SDK modules and all its submodules manually, and we have to do it for iOS/Android platforms and for Xamarin.Forms separately. Once 6.0.0 is released, updates will be rolled out automatically after critical native SDK releases.

@KevinvdBurg regarding HMS support - we are going to release the package with core functionality only first to do it as soon as possible, and then, with the very next release, we will add HMS support.

On behalf of the team, please let me apologize for all the inconvenience caused by unclear ETA and delays with the release! Releasing the updated Xamarin package is the first priority task for us right now, and we are doing our best to deliver it ASAP.

**Comment by gerardvanderkruijs** [comment] 2021-04-12 07:21
@wfhm We need this update asap! One of our apps just got removed by Google because of the use of the Pushwoosh SDK. I see this issue is fixed in the native Android SDK (6.2.5), but (obviously) not yet in the Xamarin.Android SDK.
From this point on every day it takes longer for the update is completely unacceptable! Our business is depending on our apps and now they are removed form the Play Store.
I don't care how this is fixed, give me access to beta builds or just send me a zipped file with the new Xamarin SDK, but this needs to be fixed today!

**Comment by dhiraj-shetty** [comment] 2021-04-12 07:47
I empathise with the concerns raised. We unfortunately have moved to Onesignal. It is not that everything works butterly smooth with Onesignal. But they do give timely updates.

Regards,
Dhiraj.

**Comment by makcyd** [comment] 2021-04-12 08:51
Hi everyone,  @gerardvanderkruijs,

We have issued an urgent update (5.23.0 for Xamarin Native and 5.24.0 for Xamarin Forms) to the current plugin that complies with the [upcoming Google Developer program policy changes](https://support.google.com/googleplay/android-developer/answer/10446026).

**For Native**:
https://www.nuget.org/packages/Pushwoosh.Xamarin.Droid/
https://www.nuget.org/packages/Pushwoosh.Inbox.Xamarin.Droid/
https://www.nuget.org/packages/Pushwoosh.Geozones.Xamarin.Droid/

**For Xamarin Forms**:
https://www.nuget.org/packages/Pushwoosh/
https://www.nuget.org/packages/Pushwoosh.Inbox/
https://www.nuget.org/packages/Pushwoosh.Geozones/

Let me provide some context as it seems we were taken aback by Google’s actions as well. 

We had planned a major update to the Xamarin plugin requested in this thread a while ago, and the update has already been in development so that it would become available long before the new policy takes effect.

It was not expected that Google would start flagging and removing applications a month ahead with a short or even without any notice. This was completely unexpected and beyond our control.

As soon as we got the first support requests, we have promptly issued an update to the native SDK and shortly updated all plugins, including Xamarin and Xamarin Forms.

I sincerely apologize for any inconvenience, please let us know if you need any assistance with getting the plugin updated.

PS: As @wfhm mentioned, our SDK team works on the major update to Xamarin and Xamarin forms plugin and will deliver it shortly.

Max, Pushwoosh Customer Success Team

**Comment by gerardvanderkruijs** [comment] 2021-04-12 09:46
Hi @makcyd ,
Thank you for the quick reply! I'll go ahead and update the Pushwoosh.Xamarin.Droid SDK to 5.23.0 for the removed app.
Hopefully the app will be in the Play Store again soon and the damage is manageable.

**Comment by wfhm** [comment] 2021-04-29 08:38
@gerardvanderkruijs @dhiraj-shetty @KevinvdBurg @CristianValencia

The updated package is published to Nuget, the actual version is 6.2.7. Android integration has changed, you can find the updated guide below:

https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/xamarin/xamarin-android-sdk

Also, in iOS, deprecated methods of PushManager class (setUserId and postEvent) were completely removed. The new methods are available via InAppManager class.

**Closed as completed by wfhm** 2021-04-29 08:38 UTC
Labels: 56328
