### ISSUE TITLE
app opens automatically when device receives notification

### ISSUE THREAD

**Issue by neerajyadav** [Pushwoosh/pushwoosh-xamarin#15] opened 2018-11-19 05:33 UTC
- environment = `xamarin.android`
- pushwoosh sdk = `Pushwoosh.Xamarin.Droid` `5.9.0`

Whenever device receives a notification, it opens the app forcefully. This is the error I'm receiving when app is in background.

``` log
2018-11-16 13:45:37.898 26223-26223/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adda52.rummyapp.free, PID: 26223
    java.lang.RuntimeException: Unable to start receiver com.google.android.gms.gcm.GcmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.adda52.rummyapp.free cmp=com.adda52.rummyapp.free/com.pushwoosh.GCMListenerService (has extras) }: app is in background uid UidRecord{c21962 u0a246 RCVR idle procs:1 seq(0,0,0)}
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3350)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6673)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.adda52.rummyapp.free cmp=com.adda52.rummyapp.free/com.pushwoosh.GCMListenerService (has extras) }: app is in background uid UidRecord{c21962 u0a246 RCVR idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1520)
        at android.app.ContextImpl.startService(ContextImpl.java:1476)
        at android.content.ContextWrapper.startService(ContextWrapper.java:644)
        at android.content.ContextWrapper.startService(ContextWrapper.java:644)
        at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:91)
        at com.google.android.gms.gcm.GcmReceiver.doStartService(Unknown Source:22)
        at com.google.android.gms.gcm.GcmReceiver.zze(Unknown Source:0)
        at com.google.android.gms.gcm.GcmReceiver.onReceive(Unknown Source:98)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3343)
        at android.app.ActivityThread.-wrap17(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6673) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769) 
2018-11-16 17:03:39.999 27788-27788/com.adda52.rummyapp.free E/Pushwoosh: You have firebase instance.
    Please, remove 'com.pushwoosh:pushwoosh-gcm' library from your app build.gradle.
    Or disable firebase from your project by removing "apply plugin: 'com.google.gms.google-services'" line.
    Otherwise pushwoosh library can work incorrect.
2018-11-16 17:03:43.043 27788-27861/com.adda52.rummyapp.free E/Pushwoosh: [RequestManager] ERROR: {"status_code":210,"status_message":"No hwid given","response":null}
    com.pushwoosh.internal.network.NetworkException: {"status_code":210,"status_message":"No hwid given","response":null}
        at com.pushwoosh.internal.network.e.a(Unknown Source:173)
        at com.pushwoosh.internal.network.e.a(Unknown Source:0)
        at com.pushwoosh.internal.network.f.run(Unknown Source:8)
        at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source:47)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by wfhm** [comment] 2018-11-21 11:51
Resolved via support@pushwoosh.com. The issue was caused by com.google.android.gms.gcm.GcmReceiver registered by a third party SDK.

@neerajyadav please confirm the issue is resolved.

**Closed as completed by wfhm** 2018-11-21 11:51 UTC
