### ISSUE TITLE
Android 13 Not prompting to enable notifications

### ISSUE THREAD

**Issue by michaelstonis** [Pushwoosh/pushwoosh-xamarin#36] opened 2022-11-04 15:31 UTC
I am guessing that the bindings libraries just need to be updated here as I believe the same issue has been reported (https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/180).

Right now, you have to go into the app's settings and enable them manually.

**Comment by wfhm** [comment] 2022-12-22 20:28
@michaelstonis I strongly apologize for such a delayed response!
The issue is fixed with the latest release.

**Closed as completed by wfhm** 2022-12-22 20:28 UTC
Labels: 73887
